// WARNING: This file has automatically been generated on Wed, 17 Apr 2024 17:23:44 CEST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include <unicode/utypes.h>
#include <unicode/utext.h>
#include <unicode/ubrk.h>
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

