// WARNING: This file has automatically been generated on Thu, 18 Apr 2024 10:58:19 CEST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package vorbis provides Go bindings for ICU4C.
*/
package icu
