// WARNING: This file has automatically been generated on Wed, 17 Apr 2024 17:23:44 CEST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package vorbis provides Go bindings for ICU4C.
*/
package icu
